import React from 'react';
import SingleExpartContent from '../../../components/SingleExpartContent/SingleExpartContent';

const HomeTwoExpertArea = () => {
   const card1 = {title: 'DeepSolar', subtitle: 'Project Overview', description: "DeepSolar project is a global effort led by Stanford University to collect granular data on solar PV installations across the world and analyze spatiotemporal solar adoption patterns to inform better policy design for promoting more widespread and equitable solar energy deployment. Instead of relying on traditional data collection methods, such as survey or data reporting, we apply machine learning on widely-available satellite and aerial imagery to collect granular spatial and temporal information of solar installations in a scalable, generalizable, and non-intrusive manner. Our algorithms and the aggregate-level data generated by the algorithms are publicly available.", button: "Learn More", href: "/home#workPresentation", backgroundImage: "url(https://web.stanford.edu/group/deepsolar/assets2/img/publications/grid/1127.jpg)"};
   const card2 = {title: 'DeepSolar++', subtitle: '', description: "Our original DeepSolar dataset revealed “where” solar PV systems are deployed in the U.S. In our newly-published work below called DeepSolar++, we have developed a new machine-learning-based framework that can identify and analyze both “where” and “when” solar PVs are deployed across the U.S. Specifically, we applied machine learning to historical satellite and aerial images and constructed a spatiotemporal dataset of solar PV installations in the U.S. We further analyzed the data from the perspective of technology adoption lifecycle to inform policy design for solar energy, especially for promoting solar adoption in low-income communities.", button: "Newly-Published Work", href: "https://www.cell.com/joule/fulltext/S2542-4351(22)00477-9", backgroundImage: "url(assets/img/expart/deepsolar++_background.jpeg)"};
   return (
      <>
         <section className="expart__area pt-200 wow fadeInUp" data-wow-delay=".4s">
            <div className="container">
               <div className="row">
                  <div className="col-xl-12">
                     <div className="expart__wrapper">
                        <div className="expart__nav">
                           <ul className="nav nav-pills justify-content-end" id="expart-tab" role="tablist">
                              <li className="nav-item text-center">
                                 <a className="nav-link active" id="philosophy-tab" data-bs-toggle="pill" href="#philosophy" role="tab" aria-controls="philosophy" aria-selected="true">Overview</a>
                              </li>
                              <li className="nav-item text-center">
                                 <a className="nav-link" id="work-tab" data-bs-toggle="pill" href="#work" role="tab" aria-controls="work" aria-selected="false">What's New</a>
                              </li>
                           </ul>
                        </div>
                        <div className="expart__tab">
                           <div className="tab-content" id="expart-Content">
                              <div className="tab-pane fade show active" id="philosophy" role="tabpanel" aria-labelledby="philosophy-tab">
                                 <SingleExpartContent image="1" card={card1}/>
                              </div>
                              <div className="tab-pane fade" id="work" role="tabpanel" aria-labelledby="work-tab">
                                 <SingleExpartContent image="2" card={card2}/>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </section>
      </>
   );
};

export default HomeTwoExpertArea;